services:
  jekyll:
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"  # Port required for LiveReload communication
    command: jekyll serve --livereload --force_polling --incremental
